"""Publish the audited September 10 raw inputs and globally shuffled packs.

CPU only. Run with MODAL_ENVIRONMENT=leon-dev and the modal conda environment.
The old publish_stage3_release_modal module targets obsolete intermediate packs.
"""
import hashlib
import json
from pathlib import Path
import shutil
import subprocess
import sys
import time

import modal

app = modal.App("lclm-stage3-final-hf-20260911-v3")
volume = modal.Volume.from_name("lclm-stage3-data")
agent_volume = modal.Volume.from_name("lclm-stage3-agent-outputs-v2-20260909", version=2)
image = modal.Image.debian_slim(python_version="3.11").pip_install(
    "huggingface_hub==0.35.3", "hf_xet>=1.1.5,<2", "pyarrow==21.0.0"
).env({"HF_HUB_DISABLE_PROGRESS_BARS": "1", "HF_HUB_DISABLE_XET": "1"})
ROOT = Path("/data/stage3-build-20260906")
FINAL = ROOT / "global-shuffle-20260910-v2"
PUBLICATION = ROOT / "hf-publication-20260911-v1"
REPOS = {kind: f"leonli66/stage3-final-mixture-20260910-{kind}" for kind in ("raw", "packed")}
MANIFEST_SHAS = {
    16384: "02461223c31dc5958cc742afefdd72881428253ca90af0e91d103477717a9681",
    32768: "38bbd44bd600e1c6fdcc2c4ad89cba1297ead9c156b28e03f1fad9cb0982650f",
}
EVIDENCE_SHAS = {
    "completion.json": "84da5a08fd3b25e5c2d3d6b79c714802bc8643fb4c185b8ab555b78d5f78cb09",
    "independent-audit.json": "c1937b150760babc3e26b023e3e3c89b384f48feaad0a22a90266815dfd1a357",
}
IGNORE = ["state.json", "**/state.json", ".cache/**", "**/.cache/**"]


def read_bound(path, expected=None):
    payload = Path(path).read_bytes()
    if expected and hashlib.sha256(payload).hexdigest() != expected:
        raise ValueError(f"Manifest changed: {path}")
    return json.loads(payload)


def manifests():
    return {length: read_bound(FINAL / f"packed-cs16-{length}/manifest.json", sha)
            for length, sha in MANIFEST_SHAS.items()}


def volume_path(path):
    return Path(path)


def raw_roots(doc):
    return {"base": Path("/data/stage3-final-mixture-cot50-v1"),
            "native": ROOT / "agents-transport",
            "expansion": volume_path(doc["expansion_reviewed_transport_manifest"]["transport_root"])}


def card(kind):
    common = """
This is the September 10 final training build, uploaded privately to the owner's
account. Upstream terms still apply; this mixture does not grant a replacement
license. Preserved upstream notices and source revisions are under
`source-notices/` and `provenance/`. Original build manifests retain their Modal
paths as provenance. `release.json` maps the uploaded files to their exact build
SHA256 hashes. Check `UPLOAD_STATUS.json` for verified upload completion.

The raw union has 21,722,787 examples: 20,326,114 base examples, 1,244,170 native
agent traces and 152,503 reviewed expanded agent traces. Base reasoning uses the
corrected CoT50 policy: prompts remain intact and compression is applied to the
selected reasoning text. Native agents remain uncompressed. Expanded agents use
memory segments for simulated long tool observations. Rejected and held trace
pools are excluded.

Native agents originate from `open-thoughts/OpenThoughts-Agent-SFT-100K`,
`nvidia/Nemotron-Agentic-v1` and `nvidia/Nemotron-SFT-Agentic-v2`; pinned revisions
and component counts are in `provenance/agent-source-manifest.json` and
`provenance/native-agent-report.json`. Expansion selection, source counts and
teacher streams are in `provenance/expansion-reviewed-transport-manifest.json`.
The selected expansion union retains reviewed legacy/pilot traces alongside the
new Qwen non-thinking traces; it is not exclusively generated by one model.

Decoder tokenizer: `Qwen/Qwen3-4B-Instruct-2507`, revision
`cdbee75f17c01a7cc42f958dc650907174af0554`.
Encoder tokenizer: `Qwen/Qwen3-Embedding-0.6B`, revision
`97b0c614be4d77ee51c0cef4e5f07c00f9eb65b3`.
"""
    if kind == "raw":
        return """---
pretty_name: Stage 3 final raw mixture (2026-09-10)
configs:
- config_name: base
  data_files:
  - split: train
    path: raw/base/*.parquet
- config_name: native_agents
  data_files:
  - split: train
    path: raw/native_agents/*.parquet
- config_name: expanded_agents
  data_files:
  - split: train
    path: raw/expanded_agents/*.parquet
---
# Stage 3 final raw training mixture

These are the unchanged raw input Parquet files used for the final 16k and 32k
packs. The three configurations preserve their original schemas. Raw here means
processed training examples before tokenization/packing, not the unprocessed
upstream downloads or generation debug logs. Native/expanded `messages` and
`tools` fields use lossless JSON-string transport; apply `json.loads` to string
values before applying a chat template.

```python
from datasets import load_dataset
data = load_dataset("leonli66/stage3-final-mixture-20260910-raw",
                    "native_agents", split="train", streaming=True, token=True)
```

The raw union is larger than the number of original examples retained in either
packed version: examples exceeding a version's compressed length limit were
excluded whole. The raw upload preserves them for reproducibility. Use the
[packed repository](https://huggingface.co/datasets/leonli66/stage3-final-mixture-20260910-packed)
for the ready-made training sequences.
""" + common
    return """---
pretty_name: Stage 3 final packed mixture, 16k and 32k (2026-09-10)
configs:
- config_name: packed_16k
  data_files:
  - split: train
    path: packed-cs16-16384/data/mixed/*/*.parquet
- config_name: packed_32k
  data_files:
  - split: train
    path: packed-cs16-32768/data/mixed/*/*.parquet
---
# Stage 3 final packed training mixture

| Version | Packed sequences | Original examples retained | Parquet files |
|---|---:|---:|---:|
| 16,384 | 2,278,921 | 21,463,686 | 4,452 |
| 32,768 | 1,277,010 | 21,669,429 | 2,495 |

Each sequence contains only one category: agent, reasoning or other. Completed
sequences are globally shuffled together using PCG64 seed 20260910; both native
and expanded agents are included. All shuffle positions and serialized payload
preservation were checked. Original examples overlap between versions: choose
one version, and do not concatenate them as independent examples.

Lengths count decoder positions **after 16:1 compression**, including memory
boundary tags. Decoder IDs and assistant-only labels are precomputed. Memory
strings are encoder-tokenized at runtime; memory vectors and boundary tags are
masked from prediction loss. Payloads use the LCLM LargeBinary Arrow format and
require its `DynamicPackedDataset` loader; they are not ordinary text SFT rows.

```python
from huggingface_hub import snapshot_download
root = snapshot_download(
    "leonli66/stage3-final-mixture-20260910-packed", repo_type="dataset",
    token=True, allow_patterns=["packed-cs16-32768/**", "release.json", "UPLOAD_STATUS.json"])
dataset_path = root + "/packed-cs16-32768"
```

Set LCLM `stages[3].dataset` to `dataset_path`, `max_packed_length` to 32768,
`training.compression_ratio` to 16 and `data.packed_attention_backend` to `flash`.
For 16k, select `packed-cs16-16384` and length 16384 instead. Point the loader at
the version root containing `data/mixed/`; retain file and row shuffling and
equal work across ranks. Pin the returned Hub revision for reproducible runs.

The tested LCLM build passed single-node H200:8 FSDP and DeepSpeed ZeRO-2 training
steps with both lengths. Multi-node/RDMA and full model/optimizer checkpoint
restore are not established by those checks. Use ZeRO-2 at most for this build.
The loader/source/rank audit records are included under `validation/`.

[Raw input repository](https://huggingface.co/datasets/leonli66/stage3-final-mixture-20260910-raw).
""" + common


def stage_release(kind):
    """Construct an exact allowlist; never upload intermediate data or HF state."""
    docs = manifests()
    doc = docs[32768]
    if docs[16384]["raw_input_content_sha256_manifest"] != doc["raw_input_content_sha256_manifest"]:
        raise ValueError("16k/32k raw input certificates differ")
    stage = PUBLICATION / kind / "files"
    stage.mkdir(parents=True, exist_ok=True)
    entries = {}

    def add(source, relative, sha=None, rows=None, size=None):
        source, relative = Path(source), Path(relative)
        if relative.is_absolute() or ".." in relative.parts or relative.name == "state.json":
            raise ValueError(f"Unsafe upload path: {relative}")
        target = stage / relative
        if relative.as_posix() in entries:
            raise ValueError(f"Duplicate upload path: {relative}")
        actual_size = source.stat().st_size
        if size is not None and actual_size != size:
            raise ValueError(f"Changed source size: {source}")
        if sha is None:
            sha = hashlib.sha256(source.read_bytes()).hexdigest()
        target.parent.mkdir(parents=True, exist_ok=True)
        if target.is_symlink():
            if target.resolve() != source.resolve():
                raise ValueError(f"Staging link changed: {target}")
        elif target.exists():
            raise ValueError(f"Unexpected staged file: {target}")
        else:
            target.symlink_to(source)
        entries[relative.as_posix()] = {"bytes": actual_size, "sha256": sha,
                                       "source": str(source)}
        if rows is not None:
            entries[relative.as_posix()]["rows"] = rows

    for length, m in docs.items():
        manifest_name = f"packed-cs16-{length}/manifest.json" if kind == "packed" else f"provenance/packed-cs16-{length}-manifest.json"
        add(FINAL/f"packed-cs16-{length}/manifest.json", manifest_name, MANIFEST_SHAS[length])
        if kind == "packed":
            for record in m["output_files"]:
                add(FINAL/f"packed-cs16-{length}"/record["relative_path"],
                    f"packed-cs16-{length}/{record['relative_path']}", record["sha256"],
                    record["rows"], record["bytes"])
    if kind == "raw":
        names = {"base": "base", "native": "native_agents", "expansion": "expanded_agents"}
        roots = raw_roots(doc)
        for record in doc["raw_input_content_sha256_manifest"]:
            add(roots[record["kind"]]/record["name"],
                f"raw/{names[record['kind']]}/{record['name']}", record["content_sha256"],
                record["rows"], record.get("bytes"))
    for name, sha in EVIDENCE_SHAS.items():
        value = read_bound(FINAL/name, sha)
        if not all(v["status"] == "complete" for v in value.values()):
            raise ValueError(f"Incomplete evidence: {name}")
        add(FINAL/name, f"validation/{name}", sha)
    for name in ("base-source-provenance-inspection.json", "agent-source-manifest.json",
                 "nemotron-math-task-semantics-20260909.json"):
        add(ROOT/name, f"provenance/{name}")
    add(ROOT/"agents-transport/report.json", "provenance/native-agent-report.json")
    add(ROOT/"grouped-packing-20260909-v3/source-manifest.json", "provenance/base-native-source-manifest.json")
    expansion = doc["expansion_reviewed_transport_manifest"]
    selected = read_bound(expansion["selection_path"], expansion["selection_sha256"])
    if expansion["status"] != "reviewed_complete" or expansion["rows"] != 152503:
        raise ValueError("Unexpected expansion selection")
    add(expansion["selection_path"], "provenance/expansion-selection.json", expansion["selection_sha256"])
    generated = PUBLICATION/kind/"generated"
    generated.mkdir(parents=True, exist_ok=True)
    exp_path = generated/"expansion-reviewed-transport-manifest.json"
    exp_path.write_text(json.dumps(expansion, indent=2)+"\n")
    add(exp_path, "provenance/expansion-reviewed-transport-manifest.json")
    notice_root = ROOT/"source-notices-v1"
    notices = read_bound(notice_root/"index.json")
    add(notice_root/"index.json", "source-notices/index.json")
    for record in notices["sources"]:
        for file in record["files"]:
            relative = Path(record["component"])/record["key"]/file["upstream_path"]
            path = notice_root/relative
            if hashlib.sha256(path.read_bytes()).hexdigest() != file["sha256"]:
                raise ValueError(f"Source notice changed: {relative}")
            add(path, f"source-notices/{relative}", file["sha256"], size=file["bytes"])
    readme = generated/"README.md"
    readme.write_text(card(kind))
    add(readme, "README.md")
    release = {"schema": "stage3-final-hf-publication-v1", "build": "20260910",
        "repository": REPOS[kind], "kind": kind, "visibility": "private",
        "packed_manifest_sha256": MANIFEST_SHAS, "raw_rows": 21722787,
        "files": entries, "state_json_excluded": True,
        "upload_authorization": "User requested both raw and packed under leonli66; private repositories selected."}
    release_path = generated/"release.json"
    release_path.write_text(json.dumps(release, indent=2, sort_keys=True)+"\n")
    add(release_path, "release.json")
    volume.commit()
    return stage, entries


def verify_remote(api, repo, revision, entries, stage):
    """Match every uploaded file to the frozen build's size and content hash."""
    from huggingface_hub.hf_api import RepoFile
    files = {f.path: f for f in api.list_repo_tree(repo, repo_type="dataset", revision=revision,
             recursive=True) if isinstance(f, RepoFile)}
    extra = set(files) - set(entries) - {".gitattributes", "UPLOAD_STATUS.json"}
    missing = set(entries) - set(files)
    if extra or missing:
        raise ValueError(f"Remote file selection mismatch: extra={sorted(extra)[:10]}, missing={sorted(missing)[:10]}")
    for name, entry in entries.items():
        remote = files[name]
        if remote.size != entry["bytes"]:
            raise ValueError(f"Remote size mismatch: {name}")
        if remote.lfs is not None:
            if remote.lfs.sha256 != entry["sha256"]:
                raise ValueError(f"Remote SHA256 mismatch: {name}")
        else:
            payload = (stage/name).read_bytes()
            if hashlib.sha256(payload).hexdigest() != entry["sha256"]:
                raise ValueError(f"Local metadata changed: {name}")
            oid = hashlib.sha1(f"blob {len(payload)}\0".encode()+payload).hexdigest()
            if remote.blob_id != oid:
                raise ValueError(f"Remote Git blob mismatch: {name}")
    return {"files_verified": len(entries), "bytes_verified": sum(r["bytes"] for r in entries.values()),
            "parquet_files": sum(n.endswith(".parquet") for n in entries),
            "all_sizes_and_content_hashes_match": True, "state_json_present": False}


def finalize(api, kind, entries, stage, started):
    repo = REPOS[kind]
    info = api.repo_info(repo, repo_type="dataset")
    if not info.private:
        raise ValueError("Repository visibility changed during upload")
    result = verify_remote(api, repo, info.sha, entries, stage)
    result.update(status="complete", repo_id=repo, kind=kind, verified_payload_revision=info.sha,
                  elapsed_seconds=round(time.time()-started, 1), private=True)
    commit = api.upload_file(repo_id=repo, repo_type="dataset", path_in_repo="UPLOAD_STATUS.json",
                    path_or_fileobj=json.dumps(result, indent=2).encode(),
                    commit_message="Confirm every final file size and content hash",
                    parent_commit=info.sha)
    result["revision"] = commit.oid
    (PUBLICATION/kind/"completion.json").write_text(json.dumps(result, indent=2)+"\n")
    volume.commit()
    print(json.dumps(result), flush=True)
    return result


def load_staged_release(kind):
    stage = PUBLICATION/kind/"files"
    release = read_bound(stage/"release.json")
    if release["repository"] != REPOS[kind] or release["packed_manifest_sha256"] != {str(k):v for k,v in MANIFEST_SHAS.items()}:
        raise ValueError("Unexpected staged release")
    entries = release["files"]
    payload = (stage/"release.json").read_bytes()
    entries["release.json"] = {"bytes": len(payload), "sha256": hashlib.sha256(payload).hexdigest(),
                               "source": str(stage/"release.json")}
    return stage, entries


def local_upload_queue(kind, stage, entries):
    """Keep thousands of uploader metadata/lock operations off the remote FS."""
    from concurrent.futures import ThreadPoolExecutor
    local = Path("/tmp")/f"stage3-hf-{kind}"
    local.mkdir(parents=True, exist_ok=True)
    for relative, entry in entries.items():
        target = local/relative
        target.parent.mkdir(parents=True, exist_ok=True)
        if not target.is_symlink():
            target.symlink_to(entry["source"])
    cache = stage/".cache/huggingface/upload"
    cached = list(cache.rglob("*.metadata")) if cache.exists() else []
    def restore(source):
        target = local/".cache/huggingface/upload"/source.relative_to(cache)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    with ThreadPoolExecutor(max_workers=16) as pool:
        list(pool.map(restore, cached))
    print(json.dumps({"event": "local_queue_ready", "kind": kind, "cached_files": len(cached)}), flush=True)
    return local


@app.function(image=image, cpu=2, memory=4096, timeout=3600,
              volumes={"/data": volume, "/runs": agent_volume},
              secrets=[modal.Secret.from_name("huggingface")])
def verify_uploaded(kind: str):
    """Resume only verification after an upload; incomplete files fail closed."""
    from huggingface_hub import HfApi
    if kind not in REPOS:
        raise ValueError(kind)
    stage, entries = load_staged_release(kind)
    return finalize(HfApi(), kind, entries, stage, time.time())


@app.function(image=image, cpu=16, memory=32768, timeout=86400,
              volumes={"/data": volume, "/runs": agent_volume},
              secrets=[modal.Secret.from_name("huggingface")])
def publish(kind: str):
    from huggingface_hub import HfApi, hf_hub_download
    from huggingface_hub.errors import RepositoryNotFoundError
    if kind not in REPOS:
        raise ValueError(kind)
    started = time.time()
    api = HfApi()
    if api.whoami()["name"] != "leonli66":
        raise ValueError("Unexpected HF account")
    manifests()
    stage, entries = (load_staged_release(kind) if (PUBLICATION/kind/"files/release.json").exists()
                      else stage_release(kind))
    repo = REPOS[kind]
    # A retry may only resume a repository bearing this exact immutable release.
    try:
        info = api.repo_info(repo, repo_type="dataset")
    except RepositoryNotFoundError:
        api.create_repo(repo, repo_type="dataset", private=True, exist_ok=False)
    else:
        if not info.private:
            raise ValueError("Existing destination is not private")
        remote_marker = Path(hf_hub_download(repo, "release.json", repo_type="dataset", revision=info.sha))
        if remote_marker.read_bytes() != (stage/"release.json").read_bytes():
            raise ValueError("Existing destination belongs to another release")
    api.upload_file(repo_id=repo, repo_type="dataset", path_in_repo="release.json",
                    path_or_fileobj=str(stage/"release.json"), commit_message="Bind final audited data release")
    api.upload_file(repo_id=repo, repo_type="dataset", path_in_repo="UPLOAD_STATUS.json",
                    path_or_fileobj=json.dumps({"status": "uploading", "kind": kind}).encode(),
                    commit_message="Mark upload in progress")
    print(json.dumps({"event": "upload_start", "kind": kind, "repo": repo,
                      "files": len(entries), "bytes": sum(r["bytes"] for r in entries.values())}), flush=True)
    # Keep native transfer code out of the Modal runtime's heartbeat process.
    # Standard LFS was substantially faster than Xet in the bounded shard probe.
    worker_args = PUBLICATION/kind/"upload-arguments.json"
    local = local_upload_queue(kind, stage, entries)
    worker_args.write_text(json.dumps(dict(repo_id=repo, repo_type="dataset", folder_path=str(local),
                            private=True, allow_patterns=list(entries), ignore_patterns=IGNORE,
                            num_workers=16, print_report=True, print_report_every=60)))
    subprocess.run([sys.executable, "-u", "-c",
        "import json,sys; from huggingface_hub import HfApi; "
        "HfApi().upload_large_folder(**json.load(open(sys.argv[1])))", str(worker_args)], check=True)
    # Save only HF's resumable metadata, never lock files or data copies.
    cache = local/".cache/huggingface/upload"
    def save_metadata(source):
        target = stage/".cache/huggingface/upload"/source.relative_to(cache)
        target.parent.mkdir(parents=True, exist_ok=True)
        shutil.copyfile(source, target)
    from concurrent.futures import ThreadPoolExecutor
    with ThreadPoolExecutor(max_workers=16) as pool:
        list(pool.map(save_metadata, cache.rglob("*.metadata")))
    volume.commit()
    return finalize(api, kind, entries, stage, started)


@app.function(image=image, cpu=4, memory=8192, timeout=3600,
              volumes={"/data": volume, "/runs": agent_volume}, secrets=[modal.Secret.from_name("huggingface")])
def preflight():
    import collections
    import pyarrow.parquet as pq
    from huggingface_hub import HfApi
    docs = manifests()
    m = docs[32768]
    expansion = m["expansion_reviewed_transport_manifest"]
    roots = {"base": Path("/data/stage3-final-mixture-cot50-v1"),
             "native": ROOT / "agents-transport",
             "expansion": volume_path(expansion["transport_root"])}
    summary = {"account": HfApi().whoami()["name"], "raw": {}, "packed": {}}
    grouped = collections.defaultdict(list)
    for record in m["raw_input_content_sha256_manifest"]:
        grouped[record["kind"]].append(record)
    for kind, records in grouped.items():
        root = roots[kind]
        for record in records:
            path = root / record["name"]
            if not path.is_file():
                raise FileNotFoundError(path)
            if "bytes" in record and path.stat().st_size != record["bytes"]:
                raise ValueError(f"File size changed: {path}")
        summary["raw"][kind] = {"root": str(root), "files": len(records),
            "rows": sum(r["rows"] for r in records),
            "bytes": sum((root/r["name"]).stat().st_size for r in records),
            "schema": str(pq.read_schema(root/records[0]["name"]))}
    for length, doc in docs.items():
        root = FINAL / f"packed-cs16-{length}"
        for record in doc["output_files"]:
            path = root / record["relative_path"]
            if path.stat().st_size != record["bytes"]:
                raise ValueError(f"File size changed: {path}")
        summary["packed"][length] = {"files": len(doc["output_files"]),
            "rows": doc["packed_sequences"], "bytes": sum(r["bytes"] for r in doc["output_files"])}
    notices = read_bound(ROOT / "source-notices-v1/index.json")
    summary["notices"] = [{k: r[k] for k in ("component", "key", "source_id", "revision")}
                          for r in notices["sources"]]
    summary["provenance_exists"] = {name: (ROOT/name).exists() for name in
        ("base-source-provenance-inspection.json", "agent-source-manifest.json",
         "nemotron-math-task-semantics-20260909.json")}
    PUBLICATION.mkdir(parents=True, exist_ok=True)
    (PUBLICATION / "preflight.json").write_text(json.dumps(summary, indent=2)+"\n")
    volume.commit()
    return summary


@app.local_entrypoint()
def main(action: str = "preflight"):
    if action == "preflight":
        print(json.dumps(preflight.remote(), indent=2))
    elif action in REPOS:
        print(json.dumps(publish.remote(action), indent=2))
    elif action.startswith("verify-") and action[7:] in REPOS:
        print(json.dumps(verify_uploaded.remote(action[7:]), indent=2))
    elif action == "both":
        calls = {kind: publish.spawn(kind) for kind in REPOS}
        print(json.dumps({kind: call.object_id for kind, call in calls.items()}), flush=True)
        for kind, call in calls.items():
            print(json.dumps({kind: call.get()}, indent=2), flush=True)
    else:
        raise ValueError(action)
