"""Assemble source receipts and inspect unresolved archives without releasing them."""
import hashlib
import json
import tarfile
from pathlib import Path
import modal
from data.stage3_full_modal import ROOT, image, volume

app = modal.App('lclm-stage3-source-provenance')
SOURCES_ROOT = Path('/data/stage3-agent/real-expansion/sources')
TASKS_ROOT = Path('/data/stage3-agent/real-expansion/pilots/full-20260906-v3')

@app.function(image=image, cpu=2, memory=8192, timeout=600, volumes={'/data':volume})
def assemble():
    from data.real_expansion_sources import SOURCE_SPECS
    from data.build_full_expansion_tasks_modal import SOURCES
    from data.pubmedqa_split import training_ids
    specs = {s.key:s for s in SOURCE_SPECS}
    records = []
    for key in SOURCES:
        build_path = TASKS_ROOT/(key+'.build.json')
        build = json.loads(build_path.read_text())
        record = {'source':key,'tasks':build['counts']['tasks'],'task_build':build,
                  'task_build_sha256':hashlib.sha256(build_path.read_bytes()).hexdigest()}
        if key == 'synthetic':
            record.update(source_id='LCLM synthetic expansion generator',seed=20260906,
                          upstream_revision=None,declared_license='generated by this project')
        else:
            source = SOURCES_ROOT/key
            snapshot = json.loads((source/'snapshot-manifest.json').read_text())
            if not snapshot.get('revision'):
                raise ValueError(f'Missing source revision: {key}')
            record.update(source_id=snapshot['source']['source_id'],upstream_revision=snapshot['revision'],
                          declared_license=specs[key].license,registry_notes=specs[key].notes,
                          snapshot_receipt=snapshot)
            raw = source/'raw-materialization-manifest.json'
            if raw.exists():
                record['raw_materialization_receipt'] = json.loads(raw.read_text())
            if snapshot['status'] != 'complete' and record.get('raw_materialization_receipt',{}).get('status') != 'complete':
                raise ValueError(f'No completed acquisition/materialization path: {key}')
            if key == 'pubmedqa_labeled':
                split = json.loads((source/'official-splits/split-manifest.json').read_text())
                assert len(training_ids(split)) == record['tasks'] == 450
                record['official_split'] = split
        records.append(record)
    task_manifest = json.loads((TASKS_ROOT/'manifest.json').read_text())
    result = {'status':'assembled','approved':False,'sources':records,
              'tasks':sum(r['tasks'] for r in records),'exclusions':task_manifest['exclusions'],
              'remaining_registry_sources':[s.as_manifest_record() for s in SOURCE_SPECS if s.key not in SOURCES],
              'limits':'Licenses are upstream declarations, not a legal clearance. Preserve upstream notices and review before publication.'}
    (ROOT/'expansion-source-provenance.json').write_text(json.dumps(result,indent=2)); volume.commit()
    return {'status':result['status'],'tasks':result['tasks'],
            'sources':[{k:r[k] for k in ('source','source_id','upstream_revision','declared_license','tasks')} for r in records]}

@app.function(image=image, cpu=4, memory=8192, timeout=1200, volumes={'/data':volume})
def inspect_techqa():
    archive = SOURCES_ROOT/'techqa/repository/TechQA.tar.gz'
    # No extraction: archive paths cannot escape a destination directory.
    names = []; interesting = []; samples = {}; count = 0
    with tarfile.open(archive,mode='r|gz') as stream:
        for member in stream:
            count += 1
            if len(names)<30: names.append({'name':member.name,'bytes':member.size})
            if any(word in member.name.lower() for word in ('train','question','readme','license','dev','eval')):
                if len(interesting)<100: interesting.append({'name':member.name,'bytes':member.size})
                if member.isfile() and member.size<3000000 and len(samples)<8 and member.name.endswith(('.json','.jsonl','.md','.txt')):
                    samples[member.name]=stream.extractfile(member).read(12000).decode('utf-8',errors='replace')
    result={'entries':count,'first_entries':names,'interesting_entries':interesting,'samples':samples}
    (ROOT/'techqa-archive-inspection.json').write_text(json.dumps(result,indent=2)); volume.commit()
    return result

@app.local_entrypoint()
def main(techqa:bool=False):
    print(json.dumps(inspect_techqa.remote() if techqa else assemble.remote(),indent=2))
