"""Assemble source receipts and inspect unresolved archives without releasing them."""
import hashlib
import json
import tarfile
from pathlib import Path
import modal
from data.stage3_full_modal import ROOT, image, volume

app = modal.App('lclm-stage3-source-provenance')
SOURCES_ROOT = Path('/data/stage3-agent/real-expansion/sources')
TASKS_ROOT = Path('/data/stage3-agent/real-expansion/pilots/full-20260906-v3')

@app.function(image=image, cpu=2, memory=8192, timeout=600, volumes={'/data':volume})
def assemble():
    from data.real_expansion_sources import SOURCE_SPECS
    from data.build_full_expansion_tasks_modal import SOURCES
    from data.pubmedqa_split import training_ids
    specs = {s.key:s for s in SOURCE_SPECS}
    records = []
    for key in SOURCES:
        build_path = TASKS_ROOT/(key+'.build.json')
        build = json.loads(build_path.read_text())
        record = {'source':key,'tasks':build['counts']['tasks'],'task_build':build,
                  'task_build_sha256':hashlib.sha256(build_path.read_bytes()).hexdigest()}
        if key == 'synthetic':
            record.update(source_id='LCLM synthetic expansion generator',seed=20260906,
                          upstream_revision=None,declared_license='generated by this project')
        else:
            source = SOURCES_ROOT/key
            snapshot = json.loads((source/'snapshot-manifest.json').read_text())
            if not snapshot.get('revision'):
                raise ValueError(f'Missing source revision: {key}')
            record.update(source_id=snapshot['source']['source_id'],upstream_revision=snapshot['revision'],
                          declared_license=specs[key].license,registry_notes=specs[key].notes,
                          snapshot_receipt=snapshot)
            raw = source/'raw-materialization-manifest.json'
            if raw.exists():
                record['raw_materialization_receipt'] = json.loads(raw.read_text())
            if snapshot['status'] != 'complete' and record.get('raw_materialization_receipt',{}).get('status') != 'complete':
                raise ValueError(f'No completed acquisition/materialization path: {key}')
            if key == 'pubmedqa_labeled':
                split = json.loads((source/'official-splits/split-manifest.json').read_text())
                assert len(training_ids(split)) == record['tasks'] == 450
                record['official_split'] = split
        records.append(record)
    task_manifest = json.loads((TASKS_ROOT/'manifest.json').read_text())
    result = {'status':'assembled','approved':False,'sources':records,
              'tasks':sum(r['tasks'] for r in records),'exclusions':task_manifest['exclusions'],
              'remaining_registry_sources':[s.as_manifest_record() for s in SOURCE_SPECS if s.key not in SOURCES],
              'limits':'Licenses are upstream declarations, not a legal clearance. Preserve upstream notices and review before publication.'}
    (ROOT/'expansion-source-provenance.json').write_text(json.dumps(result,indent=2)); volume.commit()
    return {'status':result['status'],'tasks':result['tasks'],
            'sources':[{k:r[k] for k in ('source','source_id','upstream_revision','declared_license','tasks')} for r in records]}

@app.function(image=image, cpu=4, memory=8192, timeout=1200, volumes={'/data':volume})
def inspect_techqa():
    archive = SOURCES_ROOT/'techqa/repository/TechQA.tar.gz'
    # No extraction: archive paths cannot escape a destination directory.
    names = []; interesting = []; samples = {}; count = 0
    with tarfile.open(archive,mode='r|gz') as stream:
        for member in stream:
            count += 1
            if len(names)<30: names.append({'name':member.name,'bytes':member.size})
            if any(word in member.name.lower() for word in ('train','question','readme','license','dev','eval')):
                if len(interesting)<100: interesting.append({'name':member.name,'bytes':member.size})
                if member.isfile() and member.size<3000000 and len(samples)<8 and member.name.endswith(('.json','.jsonl','.md','.txt')):
                    samples[member.name]=stream.extractfile(member).read(12000).decode('utf-8',errors='replace')
    result={'entries':count,'first_entries':names,'interesting_entries':interesting,'samples':samples}
    (ROOT/'techqa-archive-inspection.json').write_text(json.dumps(result,indent=2)); volume.commit()
    return result

@app.local_entrypoint()
def main(techqa:bool=False,base:bool=False):
    if techqa and base:raise ValueError('Choose one inspection mode')
    print(json.dumps(inspect_base.remote() if base else inspect_techqa.remote() if techqa else assemble.remote(),indent=2))


@app.function(image=image,cpu=4,memory=8192,timeout=1800,volumes={'/data':volume})
def inspect_base():
    import re
    from collections import Counter
    import pyarrow.parquet as pq
    from huggingface_hub import HfApi
    source=Path('/data/stage3-final-mixture')
    files=sorted(source.glob('*.parquet'));counts=Counter();metadata_rows=0
    revisions=Counter();missing_receipts=[]
    for path in files:
        parquet=pq.ParquetFile(path)
        metadata_rows+=parquet.metadata.num_rows
        for batch in parquet.iter_batches(batch_size=65536,columns=['sub_dataset']):
            counts.update(batch.column(0).to_pylist())
        receipt=source/'.cache/huggingface/download'/(path.name+'.metadata')
        if receipt.exists():
            commit=receipt.read_text().splitlines()[0]
            if not re.fullmatch('[0-9a-f]{40}',commit):raise ValueError('Unknown download receipt format')
            revisions[commit]+=1
        else:missing_receipts.append(path.name)
    if not files or metadata_rows!=sum(counts.values()):raise ValueError('Base row accounting mismatch')
    cards={}
    for revision in revisions:
        info=HfApi().dataset_info('leonli66/stage3-final-mixture',revision=revision)
        cards[revision]={'sha':info.sha,'card_data':info.card_data.to_dict() if info.card_data else {},
            'metadata_files':[s.rfilename for s in info.siblings
                if s.rfilename.lower().startswith(('readme','license','notice','copying'))]}
    report={'status':'inspected','approved':False,'source':'leonli66/stage3-final-mixture',
        'parquet_shards':len(files),'rows':metadata_rows,'sub_dataset_counts':dict(sorted(counts.items())),
        'download_receipt_revisions':dict(revisions),'missing_download_receipts':missing_receipts,
        'pinned_source_cards':cards,
        'limits':'Sub-dataset labels are not upstream IDs or license declarations. Original mixture build/source mapping is still required for complete attribution review.'}
    (ROOT/'base-source-provenance-inspection.json').write_text(json.dumps(report,indent=2));volume.commit()
    return report
